### ISSUE TITLE
Echec de compilation

### ISSUE THREAD

**Issue by samyblusseau** [boisgera/CDIS#176]
Configuration de l'environnement jointe (environment.txt car .yml non supporté ici).

Problème lors de l'exécution de build.
Cela semble venir de l'option 'projection' dans figure de matplotlib, utilisée dans fubini.py.
[environment.txt](https://github.com/boisgera/CDIS/files/5349050/environment.txt)

Erreur:

build Calcul Différentiel III/
build Calcul Intégral I/
build Calcul Intégral II/
build Calcul Intégral III/
Traceback (most recent call last):
  File ".../probas/CDIS/proba/lib/python3.7/site-packages/matplotlib/projections/__init__.py", line 58, in get_projection_class
    return projection_registry.get_projection_class(projection)
  File ".../probas/CDIS/proba/lib/python3.7/site-packages/matplotlib/projections/__init__.py", line 25, in get_projection_class
    return self._all_projection_types[name]
KeyError: '3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fubini.py", line 100, in <module>
    main()
  File "fubini.py", line 53, in main
    ax = fig.add_subplot(1, 1, 1, projection='3d')
  File ".../probas/CDIS/proba/lib/python3.7/site-packages/matplotlib/figure.py", line 1396, in add_subplot
    self._process_projection_requirements(*args, **kwargs)
  File ".../probas/CDIS/proba/lib/python3.7/site-packages/matplotlib/figure.py", line 1120, in _process_projection_requirements
    projection_class = projections.get_projection_class(projection)
  File ".../probas/CDIS/proba/lib/python3.7/site-packages/matplotlib/projections/__init__.py", line 60, in get_projection_class
    raise ValueError("Unknown projection %r" % projection)
ValueError: Unknown projection '3d'

**Comment by boisgera** [comment]
Est-ce que tu peux essayer à nouveau stp @samyblusseau  ?

**Comment by samyblusseau** [comment]
Yes ça a compilé jusqu'au bout et j'ai un poly de probas à la date d'aujourd'hui!

**Comment by samyblusseau** [comment]
Merci beaucoup !
