### ISSUE TITLE
Tmpdir Heisenbug (windows)

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#62]
Par exemple:

```
build Calcul Intégral V/
Traceback (most recent call last):
  File "./build", line 584, in <module>
    doc = transform(doc)
  File "./build", line 54, in transform
    insert_authors(doc)
  File "./build", line 126, in insert_authors
    content_inlines = pandoc.read(content)[1][0][0]
  File "c:\users\boisgera\sandbox\cdis\src\pandoc\src\pandoc\__init__.py", line 293, in read
    shutil.rmtree(tmp_dir)
  File "C:\Users\boisgera\sandbox\CDIS\env\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\boisgera\sandbox\CDIS\env\lib\shutil.py", line 401, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\boisgera\sandbox\CDIS\env\lib\shutil.py", line 399, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] Le répertoire n’est pas vide: 'C:\\Users\\boisgera\\AppData\\Local\\Temp\\tmpme2ul8wi'
```

**Comment by boisgera** [comment]
cf

  - <https://github.com/pypa/pip/issues/4910>

  - <https://www.gitmemory.com/issue/sdispater/poetry/1031/488759621>

  - <https://bugs.python.org/issue33240>
